// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntunriyijytbtfuiysbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50dW5yaXlpanl0YnRmdWl5c2JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NDA4NjgsImV4cCI6MjA2NTQxNjg2OH0.38eGRVkAlsBcJAoYjT8C9Lfs7BdxdUO0qAhkBRueGr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);